name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: NonProd
    steps:
      - 
        uses: actions/checkout@v4
    
      - 
        name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JRLMGITOPSACR_LOGIN_SERVER }}
          username: ${{ secrets.JRLMGITOPSACR_USERNAME }}
          password: ${{ secrets.JRLMGITOPSACR_PASSWORD }}

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          tags: |
            ${{ vars.JRLMGITOPSACR_LOGIN_SERVER }}/sverdle:${{ github.sha }}